# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Trail Lab' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trail Lab

  target 'Trail LabTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Trail LabUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Core'
pod 'Firebase/Auth'
end
